#!/usr/bin/env bash

export JAR=gs://hammerlab-lib/pageant-f147c5d.jar
export MAIN=org.hammerlab.pageant.coverage.CoverageDepth
export CLUSTER=pageant
"$(dirname "${BASH_SOURCE[0]}")"/../dataproc/dataproc "$@"
